Implement `Herb::Node#compact_child_nodes` (#119)
This pull request introduces changes to improve the handling of `nil`
values in `child_nodes` when traversing a tree using a Visitor. The
`compact_child_nodes` method filters out `nil` values so that the
visitor can call that method without having to handle nil values there.

Previously this would fail with something like:

```
NoMethodError: undefined method 'accept' for nil
    lib/herb/visitor.rb:21:in 'block in Herb::Visitor#visit_child_nodes'
    lib/herb/visitor.rb:21:in 'Array#each'
    lib/herb/visitor.rb:21:in 'Herb::Visitor#visit_child_nodes'
    test/visitor_test.rb:16:in 'VisitorTest::VisitedNodesVisitor#visit_child_nodes'
    lib/herb/visitor.rb:51:in 'Herb::Visitor#visit_html_element_node'
    lib/herb/ast/nodes.rb:344:in 'Herb::AST::HTMLElementNode#accept'
    lib/herb/visitor.rb:21:in 'block in Herb::Visitor#visit_child_nodes'
    lib/herb/visitor.rb:21:in 'Array#each'
    lib/herb/visitor.rb:21:in 'Herb::Visitor#visit_child_nodes'
    test/visitor_test.rb:16:in 'VisitorTest::VisitedNodesVisitor#visit_child_nodes'
    lib/herb/visitor.rb:26:in 'Herb::Visitor#visit_document_node'
    lib/herb/ast/nodes.rb:27:in 'Herb::AST::DocumentNode#accept'
    lib/herb/parse_result.rb:32:in 'Herb::ParseResult#visit'
    test/visitor_test.rb:46:in 'block in <class:VisitorTest>'
```